remote_theme: pages-themes/minimal@v0.2.0
#plugins: jekyll-remote-theme
title: Antoine Haddad
description: Explorez mon monde créatif à travers mon portfolio en ligne.
logo: /assets/img/profil.png
show_downloads: true
